/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kapitel_11_demo;

import kapitel_11_struktur_i_en_gui.FanerPanel;

/**
 *
 * @author j
 */
public class JacobPanel extends javax.swing.JPanel {
	FanerPanel fanerPanel;

	/** Creates new form JacobPanel */
	public JacobPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    okKnap = new javax.swing.JButton();
    ærlighedindikator = new javax.swing.JCheckBox();
    kloghedsinidkator = new javax.swing.JSlider();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaDom = new javax.swing.JTextArea();
    jComboBox1 = new javax.swing.JComboBox();
    jButton1 = new javax.swing.JButton();

    jLabel1.setText("Hvor klog er du?");

    okKnap.setText("OK");
    okKnap.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okKnapActionPerformed(evt);
      }
    });

    ærlighedindikator.setText("Jeg er ærlig nu");

    kloghedsinidkator.setMaximum(70);
    kloghedsinidkator.setValue(5);
    kloghedsinidkator.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        kloghedsinidkatorStateChanged(evt);
      }
    });

    jTextAreaDom.setColumns(20);
    jTextAreaDom.setRows(5);
    jScrollPane1.setViewportView(jTextAreaDom);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Søren", "Jacob", "Bo", "Ib" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jButton1.setText("Skift fane");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        skiftFane(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(71, 71, 71)
        .addComponent(jLabel1)
        .addGap(5, 5, 5)
        .addComponent(okKnap)
        .addGap(5, 5, 5)
        .addComponent(ærlighedindikator))
      .addGroup(layout.createSequentialGroup()
        .addGap(109, 109, 109)
        .addComponent(kloghedsinidkator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(layout.createSequentialGroup()
        .addGap(173, 173, 173)
        .addComponent(jButton1))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(5, 5, 5)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel1))
          .addComponent(okKnap)
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(ærlighedindikator)))
        .addGap(5, 5, 5)
        .addComponent(kloghedsinidkator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(5, 5, 5)
        .addComponent(jButton1))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void okKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okKnapActionPerformed

		System.out.println("okKnapActionPerformed blev kaldt");
		int kloghed = kloghedsinidkator.getValue();
		boolean ærlig = ærlighedindikator.isSelected();

		if (kloghed > 60) {
      if (ærlig) jTextAreaDom.setText("Din pralhals!!");
      else jTextAreaDom.setText("Din løgner!!");
		} else if (kloghed < 20) {
			jTextAreaDom.setText("Nu er du for beskedden :-)");
		} else {
			jTextAreaDom.setText("Ikke klog, ikke dum.");
    }
    jTextAreaDom.append("\n\nklog: "+kloghed+" ærlig="+ærlig);

  }//GEN-LAST:event_okKnapActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		if (jComboBox1.getSelectedIndex()<3) {
			okKnap.setEnabled(true);
		} else {
			okKnap.setEnabled(false);
		}
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void skiftFane(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skiftFane
		// TODO add your handling code here:
		System.out.println("skiftFane blev trykket");
		fanerPanel.skiftTilFane(0);
  }//GEN-LAST:event_skiftFane

  private void kloghedsinidkatorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kloghedsinidkatorStateChanged
    // TODO add your handling code here:

		int n = kloghedsinidkator.getValue();
		System.out.println("kloghedsinidkator n="+n);
  }//GEN-LAST:event_kloghedsinidkatorStateChanged



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextAreaDom;
  private javax.swing.JSlider kloghedsinidkator;
  private javax.swing.JButton okKnap;
  private javax.swing.JCheckBox ærlighedindikator;
  // End of variables declaration//GEN-END:variables

  public void setKloghedsinidkator(int kloghed) {
    kloghedsinidkator.setValue(kloghed);
  }

  public int getKloghedsinidkator() {
    return kloghedsinidkator.getValue();
  }


  private String labelTekst;

  public String getLabelTekst() {
    return labelTekst;
  }

  public void setLabelTekst(String labelTekst) {
    this.labelTekst = labelTekst;
    jLabel1.setText(labelTekst);
  }
}
