/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kapitel_11_struktur_i_en_gui;

import kapitel_04.Billetautomat;

/**
 *
 * @author j
 */
public class FanerPanel extends javax.swing.JPanel {

	private Billetautomat automatlogik;

	/** Creates new form MangePaneler */
	public FanerPanel() {
		initComponents();

		// Skjul fanebladene
		/*
		jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
			protected int calculateTabAreaHeight(int t, int h, int m) {
				return 0;
			}
		});
		*/

		// Fortæl hvert panel hvem dets ejer er
		velkomstPanel1.setFanerPanel(this);
		indkastPengePanel1.setFanerPanel(this);
		udskrivBilletPanel1.setFanerPanel(this);
	}

	public void setAutomatlogik(Billetautomat ba) {
		automatlogik = ba;
	}

	public Billetautomat getAutomatlogik() {
		return automatlogik;
	}

	public void skiftTilFane(int fane) {
		jTabbedPane1.setSelectedIndex(fane);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    velkomstPanel1 = new kapitel_11_struktur_i_en_gui.VelkomstPanel();
    indkastPengePanel1 = new kapitel_11_struktur_i_en_gui.IndkastPengePanel();
    udskrivBilletPanel1 = new kapitel_11_struktur_i_en_gui.UdskrivBilletPanel();

    setLayout(new java.awt.BorderLayout());

    jTabbedPane1.addTab("tab1", velkomstPanel1);
    jTabbedPane1.addTab("tab2", indkastPengePanel1);
    jTabbedPane1.addTab("tab3", udskrivBilletPanel1);

    add(jTabbedPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private kapitel_11_struktur_i_en_gui.IndkastPengePanel indkastPengePanel1;
  private javax.swing.JTabbedPane jTabbedPane1;
  private kapitel_11_struktur_i_en_gui.UdskrivBilletPanel udskrivBilletPanel1;
  private kapitel_11_struktur_i_en_gui.VelkomstPanel velkomstPanel1;
  // End of variables declaration//GEN-END:variables

}
