/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kapitel_11_struktur_i_en_gui;

/**
 *
 * @author j
 */
public class MangePaneler extends javax.swing.JPanel {
	/** Creates new form MangePaneler */
	public MangePaneler() {
		initComponents();
		jacobPanel1.ejer = this;
	}

	public void sætFane(int fane) {
		jTabbedPane1.setSelectedIndex(fane);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    java2DDemo1 = new kapitel_09.Java2DDemo();
    grafikpanel1 = new kapitel_09.Grafikpanel();
    grafikpanel2 = new kapitel_09.Grafikpanel();
    jacobPanel1 = new kapitel_11_struktur_i_en_gui.JacobPanel();

    setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout java2DDemo1Layout = new javax.swing.GroupLayout(java2DDemo1);
    java2DDemo1.setLayout(java2DDemo1Layout);
    java2DDemo1Layout.setHorizontalGroup(
      java2DDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 491, Short.MAX_VALUE)
    );
    java2DDemo1Layout.setVerticalGroup(
      java2DDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 306, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Java 2D demo", java2DDemo1);

    javax.swing.GroupLayout grafikpanel1Layout = new javax.swing.GroupLayout(grafikpanel1);
    grafikpanel1.setLayout(grafikpanel1Layout);
    grafikpanel1Layout.setHorizontalGroup(
      grafikpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 491, Short.MAX_VALUE)
    );
    grafikpanel1Layout.setVerticalGroup(
      grafikpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 306, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Grafikpanel 1", grafikpanel1);

    javax.swing.GroupLayout grafikpanel2Layout = new javax.swing.GroupLayout(grafikpanel2);
    grafikpanel2.setLayout(grafikpanel2Layout);
    grafikpanel2Layout.setHorizontalGroup(
      grafikpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 491, Short.MAX_VALUE)
    );
    grafikpanel2Layout.setVerticalGroup(
      grafikpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 306, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Grafikpanel 2", grafikpanel2);
    jTabbedPane1.addTab("JacobPanel", jacobPanel1);

    add(jTabbedPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private kapitel_09.Grafikpanel grafikpanel1;
  private kapitel_09.Grafikpanel grafikpanel2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private kapitel_11_struktur_i_en_gui.JacobPanel jacobPanel1;
  private kapitel_09.Java2DDemo java2DDemo1;
  // End of variables declaration//GEN-END:variables
}
